/** @type {import('jest').Config} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["<rootDir>/test/setup.ts"],
  moduleNameMapper: {
    // `styled-system` is generated by `panda codegen` into the repo root, and
    // resolved via tsconfig baseUrl at typecheck time. Jest does not read
    // baseUrl, so it needs the mapping spelled out or every component import
    // dies with "Cannot find module 'styled-system/jsx'".
    "^styled-system/(.*)$": "<rootDir>/styled-system/$1",
  },
  // `.mjs` is listed so the generated styled-system resolves and, below, gets
  // transformed. Without it Jest cannot even find `styled-system/jsx`.
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "mjs", "json"],
  transform: {
    // The generated styled-system is ESM. Jest runs CJS, so it MUST be
    // transpiled — hence `.mjs` in the pattern and `allowJs`.
    //
    // This is the one place worth not copying from the app this was extracted
    // from: there, `styled-system/*` is mocked wholesale in Jest, which means no
    // unit test can assert anything a recipe produces (documented as a hard
    // constraint in its PRD-0013). Transforming the real generated output
    // instead costs a few ms per suite and makes recipe behaviour testable.
    "^.+\\.(t|j)sx?$|^.+\\.mjs$": [
      "ts-jest",
      {
        tsconfig: {
          jsx: "react-jsx",
          allowJs: true,
        },
      },
    ],
  },
  testMatch: ["<rootDir>/src/**/__tests__/**/*.test.{ts,tsx}"],
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/**/__tests__/**",
    "!src/index.ts",
    "!src/**/index.ts",
  ],
};
