/**
 * Playwright component-test entry point.
 *
 * Two imports, both load-bearing:
 *
 * 1. **The generated stylesheet.** Panda emits every recipe class here. Without
 *    it components mount with correct class names and no rules behind them, so
 *    every layout assertion measures an unstyled box. Generated by
 *    `npm run panda:build`, which `pretest:ct` runs.
 *
 * 2. **A theme.** Every colour token resolves to a bare CSS custom property, so
 *    a page that defines none renders the whole system invisible — see
 *    semantic-variables.ts. `theme.css` supplies all 44, and a jest test
 *    asserts it stays complete.
 */
import "../styled-system/styles.css";
import "./reset.css";
import "./theme.css";
